# Generated by Django 3.2.22 on 2024-02-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
