# Generated by Django 3.2.22 on 2024-02-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
