# Generated by Django 3.2.22 on 2024-02-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_buyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='timestamp',
        ),
    ]
