# Generated by Django 3.2.22 on 2024-02-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_buyproduct_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
