# Generated by Django 3.2.22 on 2024-02-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_buyproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='price',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='price',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
